services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('add_category/', views.add_category, name='add_category'),
    path('list_category/', views.list_category, name='list_category'),
    path('create_service/', views.create_service, name='create_service'),
    path('get_services/', views.get_home_services, name='get_services'),
    path('service_details/<uuid:id>/', views.service_details, name='service_details'),
    path('add_review/', views.add_review, name='add_review'),
    path('request_service/', views.request_service, name='request_service'),
    path('update_is_read/<uuid:id>/', views.update_is_read, name='update_is_read'),
    path('category_services/<uuid:category_id>/', views.category_services, name='category_services'),
    path('search_view/', views.search_view, name='search_view'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('dashboard/<str:id>/', views.dashboard, name='dashboard'),
    path('signup', views.signup_view, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('groups/', views.group_list, name='group_list'),
    path('groups/<str:group_name>/', views.view_group_users, name='group_users'),
    path('new_group/', views.add_group, name='new_group'),
    path('user_profile/', views.create_user_profile, name='user_profile'),
    path('view_profile/', views.view_user_profile, name='view_profile'),
    path('others_profile/<uuid:id>/', views.view_others_profile, name='others_profile'),
    path('all_users/', views.list_all_users, name='all_users'),
    path('save_education/', views.add_user_education, name='save_education'),
]

we_connect_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include('users.urls', namespace='users')),
    path('services/', include('services.urls', namespace='services')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
import uuid
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, Permission
from django.core.mail import send_mail
from django.db import models
from .manager import UserAccountManager


#class UserPermission(Permission):
    #class Meta:
        #app_label = 'users'
        #permissions =[('do_all', 'Can do all'), ('add_users', 'Can add users'), ('edit_table', 'Can edit table')]


# Create your models here.
User = settings.AUTH_USER_MODEL


class CustomUser(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(max_length=255, unique=True, db_index=True, verbose_name="Email")
    first_name = models.CharField(max_length=255, verbose_name="First Name")
    last_name = models.CharField(max_length=255, verbose_name="Last Name")
    username = models.CharField(max_length=50, verbose_name='Username', null=True, blank=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_login = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserAccountManager()

    class Meta:
        ordering = ('date_joined',)
        verbose_name = "Custom User"
        verbose_name_plural = "Custom Users"

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.last_name} {self.first_name}'

    def get_short_name(self):
        return self.username

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_user_permissions(self, obj=None):
        """
            Return a list of permission strings that this user has.
        """
        if not self.is_active or self.is_anonymous:
            return set()

        # Retrieve user permissions from groups
        permissions = self.get_group_permissions(obj)

        # Retrieve user-specific permissions
        user_permissions = [perm.codename for perm in self.user_permissions.all()]

        # Combine and return the permissions
        permissions.update(user_permissions)
        return permissions

    def get_all_permissions(self, obj=None):
        return self.get_user_permissions(obj)


class Education(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    school = models.CharField(max_length=255)
    qualification = models.CharField(max_length=255)
    course = models.CharField(max_length=255, verbose_name='Course Of Study')
    graduation_year = models.DateField()

    def __str__(self):
        return f'Education for {self.user.email}'


class UserProfile(models.Model):
    Gender = [
        ('Male', 'Male'),
        ('Female', 'Female')
    ]

    Marital_Status = [
        ("Single", "Single"),
        ('Married', 'Married'),
        ('Divorced', 'Divorced'),
        ('Widow', 'Widow'),
        ('Others', 'Others')
    ]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    i_am_a = models.CharField(max_length=50, verbose_name="I Am A")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.PositiveSmallIntegerField(default=1)
    bio = models.CharField(max_length=450, verbose_name="Biography")
    phone_number = models.CharField(max_length=20, verbose_name='Phone Number')
    gender = models.CharField(choices=Gender, max_length=10)
    profile_pics = models.ImageField(upload_to='profile_pics', default='img/default_pic.png')
    highest_education = models.ManyToManyField(Education, verbose_name='Education Qualification')
    occupation = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

    def __str__(self):
        return f'Profile for {self.user.first_name} {self.user.last_name}'

users/views.py
import json
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from services.models import Service
from .models import CustomUser as User, UserProfile, Education
from .decorators import is_service_provider, superuser_required
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator

@login_required
def home(request):
    all_services = Service.objects.all()
    paginator = Paginator(all_services, 4)
    page = request.GET.get('page')
    services = paginator.get_page(page)
    context = {
        'services': services, 'user': request.user.username
    }
    return render(request, 'users/home.html', context)

@login_required
@is_service_provider
def dashboard(request, id):
    profile = UserProfile.objects.get(user__id=id)
    services = Service.objects.filter(user=profile)
    return render(request, 'users/dashboard.html', {'services': services})


def signup_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password = request.POST['password']
        password1 = request.POST['password1']

        # validate email
        email = email.strip().lower()
        if ("@" not in email) or (email[-4:] not in ".com.org.edu.gov.net"):
            messages.error(request, 'Your Email, ' + email + ', Is Invalid!!!')
            return render(request, 'users/signup.html')
        if User.objects.filter(email=email).exists():
            messages.error(request, 'Your Email, ' + email + ', Already Exists. Please Try Another Email')
            return render(request, 'users/signup.html')
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Your Username, ' + username + ', Already Exists. Please Try Another Username')
            return render(request, 'users/signup.html')

        # validate password
        if password != password1:
            messages.error(request, "Your Passwords Don't match")
            return render(request, 'users/signup.html')
        user = User.objects.create_user(email=email, first_name=first_name, last_name=last_name, username=username, password=password)
        if user.email == 'akinade.mayowa@gmail.com' and user.password == 'mayowafunmi':
            user.is_superuser = True
        user_group = Group.objects.get(name="Users")
        user.groups.add(user_group)
        messages.success(request, "User Registration Successful")
        context = {
            'email': email, 'first_name': first_name, 'last_name': last_name, 'username': username, "password": password, "password1": password1
        }
        return render(request, 'users/success.html', context)

    return render(request, 'users/signup.html')


# view for login
def user_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        # validate email
        email = email.strip().lower()
        if ("@" not in email) or (email[-4:] not in ".com.org.edu.gov.net"):
            messages.error(request, 'Your Email, ' + email + ', Is Invalid!!!')
            return render(request, 'users/login.html')
        # email is valid but does not exist
        if not User.objects.filter(email=email).exists():
            messages.error(request, 'This email, ' + email + ', Does Not Exist...')
            return render(request, 'users/login.html')
        else:
            user = authenticate(request, username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, "You are logged in successfully")
                    if user.groups.filter(name='Customer').exists():
                        return redirect('/users/home/')
                    elif user.groups.filter(name='Service Provider').exists():
                        return redirect('/users/dashboard/'+str(user.id)+'/')
                    else:
                        return redirect('/users/user_profile/')
                else:
                    messages.error(request, "email or password incorrect")
            else:
                messages.error(request, f"User with email '{email}' does not exist")
    return render(request, 'users/login.html')


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, "You are logged out successfully")
    return HttpResponseRedirect('/users/login/')


# list all available groups
@login_required
@superuser_required
def group_list(request):
    groups = Group.objects.all()
    context = {
        'groups': groups
    }
    return render(request, 'users/groups/group_list.html', context)

@login_required
@superuser_required
def view_group_users(request, group_name):
    try:
        group = Group.objects.get(name=group_name)
    except Group.DoesNotExist:
        messages.error(request, f"The group '{group_name}' does not exist")
        return render(request, 'users/groups/group_users_list.html', {'users': []})

    users = group.user_set.all()
    context = {
        'users': users,
        'group_name': group_name
    }
    return render(request, 'users/groups/group_users_list.html', context)


@login_required
@superuser_required
def add_group(request):
    if request.method == 'POST':
        name = request.POST['group_name']
        group_name = name.title()
        request_group, created = Group.objects.get_or_create(name=group_name)
        messages.success(request, f'{group_name} Group Created Successfully')
        return HttpResponseRedirect('/users/groups/')
    return render(request, 'users/groups/new_group.html')

# add users to specific groups based on user status in user profiles. check the signup view


@login_required
@superuser_required
def add_user_to_group(user, group):
    try:
        user.groups.add(group)
        user.save()
        return True
    except:
        return False

@login_required
@csrf_exempt
def add_user_education(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            user_id = data.get('user_id')
            qualifications = data.get('qualifications')
            if not qualifications or not isinstance(qualifications, list):
                return JsonResponse({'status': 'error', 'message': 'Invalid qualifications data'})
            
            for qualification_data in qualifications:
                school = qualification_data.get('school')
                qualification = qualification_data.get('qualification')
                course = qualification_data.get('course')
                graduation_year = qualification_data.get('graduation_year')

                if not school or not qualification or not course or not graduation_year:
                    return JsonResponse({'status': 'error', 'message': 'Incomplete qualification data'})
                
                Education.objects.create(
                    user = request.user, school=school, qualification=qualification, course=course, graduation_year=graduation_year
                )
            return JsonResponse({'status': 'success', 'message': 'User Education Qualifications Saved Successfully'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
    return JsonResponse({'status': 'error'}, status=400)

@login_required
def create_user_profile(request):
    req_user = request.user
    groups = Group.objects.all()
    g = [group.name for group in groups if group.name != "Super Admin" and group.name != "Admin" and group.name != 'Users']
    if hasattr(req_user, 'userprofile'):
        return HttpResponseRedirect('/users/view_profile')
    else:
        #messages.info(request, 'Create Your Profile')
        if request.method == 'POST':
            i_am_a = request.POST['i_am_a']
            user = req_user
            bio = request.POST['bio'] 
            phone_number = request.POST['phone_number']
            gender = request.POST['gender']
            profile_pics = request.FILES['profile_pics']
            occupation = request.POST['occupation']
            address = request.POST['address']
            user_group = Group.objects.get(name=i_am_a)
            user = User.objects.get(id=request.user.id)
            user.groups.add(user_group)
            user.save()
            try:
                profile = UserProfile(
                    i_am_a=i_am_a, user=user, bio=bio, phone_number=phone_number, gender=gender,
                    profile_pics=profile_pics, occupation=occupation, address=address
                )
                profile.save()
                educations = Education.objects.filter(user=request.user)
                for education in educations:
                    profile.highest_education.add(education)
                messages.success(request, 'Profile Created Successfully')
                if user.groups.filter(name='Customer').exists():
                    return redirect('/users/home/')
                elif user.groups.filter(name='Service Provider').exists():
                    return redirect('/users/user_profile/') # change this to dashboard for user services
                else:
                    return redirect('/users/user_profile/')
            except:
                messages.error(request, 'Failed To Create Your Profile')
                return render(request, 'users/user_profile.html')
        return render(request, 'users/user_profile.html', {'groups': g})


@login_required
def view_user_profile(request):

users/templates/users/all_users.html
{% extends 'users/base.html' %}

{% block title %}All Users{% endblock title %}

{% block header %}
  <h2 class="text-center">All Users List - {{ users.count }} </h2>
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block content %}
  <div class="list-group">
    {% for user in users %}
      <a href="{% url 'users:others_profile' user.id %}" class="list-group-item list-group-item-action">{{ user.first_name }} {{ user.last_name}}</a>
    {% endfor %}
  </div>
{% endblock content %}

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home | WeConnect App{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- One file includes all the Font Awesome Free icons and utilities -->
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container-fluid">
        <!-- Start Naigation bar -->
        <nav class="container navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'users:home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                  {% if request.user.groups.all %}
                    {% for group in request.user.groups.all %}
                      {% if group.name == "Service Provider" %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'users:dashboard' request.user.id %}">Dashboard</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'services:create_service' %}">Sell</a>
                        </li>
                      {% endif %}
                    {% endfor %}
                  {% endif %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:user_profile' %}">Profile</a>
                  </li>
                  <button type="button" data-bs-toggle="modal" data-bs-target="#inboxModal" class="btn btn-primary position-relative">
                    Inbox
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                     {{ unread.count }}
                      {% comment %} <span class="visually-hidden">unread messages</span> {% endcomment %}
                    </span>
                  </button>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signup' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                  </li>
                {% endif %}
                {% if request.user.is_superuser %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Super User
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/admin/">Admin Site</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'users:group_list' %}">User Groups</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'services:list_category' %}">Category</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'users:all_users' %}">All Users</a></li>
                    </ul>
                  </li>
                {% endif %}
              </ul>

              <form class="d-flex" role="search" action="{% url 'services:search_view' %}" method="GET">
                <input class="form-control me-2" type="search" name="q" placeholder="Search for services" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>

        <div class="modal fade" id="inboxModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Messages</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body" id="modal_body">
                <div class="card">
                  {% if unread %}
                    <p><strong>Unread</strong>></p>
                    <ul id="unread_messages" class="list-group list-group-flush">
                      {% for msg in unread %}
                        <a href="{% url 'services:service_details' msg.service.id %}" id="unread_msg" data-service-id="{{ msg.service.id }}" onclick="return handleClick(event);">
                          <li class="list-group-item"><span><strong>@{{ msg.sender.username}}: {{ msg.message }}</strong></span></li>
                        </a>
                      {% endfor %}
                    </ul>
                  {% elif read %}
                    <p><strong>Read</strong></p>
                    <ul id="read_messages" class="list-group list-group-flush">
                      {% for msg in read %}
                        <a href="{% url 'services:service_details' msg.service.id %}">
                          <li class="list-group-item">@{{ msg.sender.username}}: {{ msg.message }}</li>
                        </a>
                      {% endfor %}
                    </ul>
                  {% else %}
                    <p>No message</p>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- End Naigation bar -->
        
        <div class="container mt-3 mb-3">
          <div class="btn-group btn-group-lg" role="group" aria-label="Large button group">
            {% for category in categories %}
              <button id="btn_link" type="button" class="btn btn-outline-primary"><a id='category_link' href="{% url 'services:category_services' category.id %}">{{ category.name }}</a></button>
            {% endfor %}
          </div>
        </div>

        {% block header %}
            <h2>Welcome to WeConnect App.</h2>
            <h3>We connect buyers and sellers</h3>
        {% endblock header %}

        {% block all_content %}
        <div class="row">
          <div class="col-8">
            {% block content %}
            {% endblock content %}
          </div>

          <div class="col-4">
            <h3>Something else here</h3>
          </div>
        </div>
        {% endblock all_content %}

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
        <script src="{% static 'js/base.js' %}"></script>
        {% block js %}
        {% endblock js %}
    </div>
</body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}Home | WeConnect App{% endblock title %}

{% block header %}
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block all_content %}
    <h5>Welcome, {{ user }}!. Find A Service Provider...</h5>

    {% if services %}
      <div class="pagination-wrapper">
        <div class="pagination">
          <span class="step-links">
            {% if services.has_previous %}
              <a href="?page={{ services.previous_page_number }}"><i class="fa-solid fa-arrow-left"></i></a>
            {% endif %}

            {% if services.has_next %}
              <a href="?page={{ services.next_page_number }}"><i class="fa-solid fa-arrow-right"></i></a>
            {% endif %}
          </span>
        </div>
      </div>
  
      <div class="container text-center">
        <div class="row">
          {% for service in services %}
            <div class="col">
              <a class="link-underline-light link-dark" href="{% url 'services:service_details' service.id %}">
                <div class="card mb-2" style="width: 15rem;">
                  <img src="{{ service.picture.url }}" class="card-img-top service_image" alt="...">
                  <div style="display: flex; flex-grow: 1; justify-content: space-between; align-items: center;">
                    <div style="display: flex; flex-direction: row;">
                      <img src="{{ service.user.profile_pics.url }}" alt="Profile Picture" style="width: 40px; height: 40px; border-radius: 50%; margin-right: 10px;">
                      <h6 class="card-subtitle text-body-secondary">{{ service.user.user.username}}</h6>
                    </div>
                    <h6 class="card-subtitle text-body-secondary">Level {{ service.user.level }}</h6>        
                  </div>
                  <div class="card-body">
                    <h6 class="card-title">{{ service.title }}</h6>
                    <div style="display: flex; justify-content: space-between;">
                      <div style="display: flex; flex-direction: row;">
                        <p class="card-subtitle text-body-secondary text-start"><i class="fa-solid fa-star"></i></p>
                        <p>{{ service.average_rating }} ({{ service.total_reviews }})</p>
                      </div>
                      <p><strong>From <i class="fa-solid fa-naira-sign"></i>{{ service.price }}</strong></p>
                    </div>
                    <div style="display: flex; justify-content: space-between; text-decoration: none">
                      {% for category in service.category.all %}
                        <a id="category_link" href="{% url 'services:category_services' category.id %}" class="card-link">{{ category.name }}</a>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    {% else %}
      <p>No Service Content </p>
    {% endif %}

{% endblock all_content %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block title %}Login Page{% endblock title %}

{% block header %}
  <h2 class="text-center">Login Form</h2>
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}

    <div class="input-group mb-3">
      <span class="input-group-text">
        <i class="fa-solid fa-envelope"></i>
      </span>
      <input type="email" name="email" class="form-control" placeholder="Enter Your Email Address" aria-label="Username" aria-describedby="basic-addon1" required>
    </div>

    <div class="input-group mb-3">
      <span class="input-group-text">
        <i class="fa-solid fa-lock"></i>
      </span>
      <input type="password" name="password" class="form-control" placeholder="Enter Your Password" aria-label="Username" aria-describedby="basic-addon1" required>
    </div>

    <button type="submit" class="btn btn-success">Login</button>
  </form>
{% endblock content %}

users/templates/users/success.html
{% extends 'users/base.html' %}

{% block title %}Registration Successful{% endblock title %}

{% block header %}
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block content %}

{% endblock content %}

users/templates/users/unauthorized.html
{% extends 'users/base.html' %}

{% block title %}Unauthorized Page{% endblock title %}

{% block header %}
  <h2 class="text-center">Unauthorized!!!</h2>
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}