services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('add_category/', views.add_category, name='add_category'),
    path('list_category/', views.list_category, name='list_category'),
    path('create_service/', views.create_service, name='create_service'),
    path('get_services/', views.get_home_services, name='get_services'),
    path('service_details/<uuid:id>/', views.service_details, name='service_details'),
    path('add_review/', views.add_review, name='add_review'),
    path('request_service/', views.request_service, name='request_service'),
    path('update_is_read/<uuid:id>/', views.update_is_read, name='update_is_read'),
    path('category_services/<uuid:category_id>/', views.category_services, name='category_services'),
    path('search_view/', views.search_view, name='search_view'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('dashboard/<str:id>/', views.dashboard, name='dashboard'),
    path('signup', views.signup_view, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('groups/', views.group_list, name='group_list'),
    path('groups/<str:group_name>/', views.view_group_users, name='group_users'),
    path('new_group/', views.add_group, name='new_group'),
    path('user_profile/', views.create_user_profile, name='user_profile'),
    path('view_profile/', views.view_user_profile, name='view_profile'),
    path('others_profile/<uuid:id>/', views.view_others_profile, name='others_profile'),
    path('all_users/', views.list_all_users, name='all_users'),
    path('save_education/', views.add_user_education, name='save_education'),
]

we_connect_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include('users.urls', namespace='users')),
    path('services/', include('services.urls', namespace='services')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/models.py
import uuid
from datetime import timedelta
from django.db import models
from users.models import UserProfile, CustomUser as User
from django.db.models import Avg


# Create your models here.
class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Service(models.Model):
    DURATION_CHOICES = (
        ('hours', 'Hours'),
        ('days', 'Days'),
        ('weeks', 'Weeks'),
        ('months', 'Months'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=255)
    description = models.TextField()
    picture = models.ImageField(upload_to="service_pics")
    price = models.DecimalField(default=0, decimal_places=2, max_digits=11)
    duration_quantity = models.PositiveIntegerField(default=1)
    duration_unit = models.CharField(choices=DURATION_CHOICES, max_length=10, default='hours')
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)
        verbose_name = 'Service'
        verbose_name_plural = 'Services'

    def __str__(self):
        return f'{self.title} by {self.user.user.username}'

    def get_duration(self):
        if self.duration_unit == 'hours':
            return timedelta(hours=self.duration_quantity)
        elif self.duration_unit == 'days':
            return timedelta(days=self.duration_quantity)
        elif self.duration_unit == 'weeks':
            return timedelta(weeks=self.duration_quantity)
        elif self.duration_unit == 'months':
            return timedelta(weeks=self.duration_quantity * 4)
        
    def total_reviews(self):
        return Review.objects.filter(service=self).count()
    
    def average_rating(self):
        average = Review.objects.filter(service=self).aggregate(Avg('rating'))['rating__avg']
        return round(average, 2) if average else 0

class Review(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    rating = models.CharField(max_length=5)
    comment = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created', )
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    def __str__(self):
        return f'Review by {self.reviewer} for {self.service.title}'


class Buyer(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    seller = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='sellers')
    buyer = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='buyers')
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    started = models.DateTimeField(auto_now_add=True)
    finished = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Contract between buyer "{self.buyer.user.username}" and seller "{self.seller.user.username}"'


class DirectMessage(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['timestamp']

    def formatted_timestamp(self):
        return self.timestamp.strftime('%I:%M%p %A %d %B, %Y')

    def __str__(self):
        return f"From: {self.sender.username}, To: {self.receiver.username}, Sent at: {self.formatted_timestamp()}"

services/views.py
import json
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from .models import Category, DirectMessage, Order, Review, Service
from .decorators import service_providers_only
from users.decorators import superuser_required
from django.core.paginator import Paginator
from django.db.models import Avg
from users.models import CustomUser as User, UserProfile
from django.db.models import Q

@login_required
@superuser_required
def add_category(request):
    if request.method == 'POST':
        category = request.POST['category']
        Category.objects.create(name=category)
        messages.success(request, 'Category Created Successfully')
        return HttpResponseRedirect('/services/list_category')
    return render(request, 'services/add_category.html')


@login_required
@superuser_required
def list_category(request):
    categories = Category.objects.all()
    return render(request, 'services/list_category.html', {'categories': categories})


@login_required
@service_providers_only
def create_service(request):
    if request.method == 'POST':
        selected_categories = request.POST.getlist('categories')
        title = request.POST['title']
        description = request.POST['description']
        picture = request.FILES['picture']
        price = request.POST['price']
        duration_quantity = request.POST['duration_quantity']
        duration_unit = request.POST['duration_unit']
        try:
            service = Service(
                user=request.user.userprofile, title=title, description=description, picture=picture, price=price,
                duration_quantity=duration_quantity, duration_unit=duration_unit
            )
            service.save()

            for category_id in selected_categories:
                category = Category.objects.get(id=category_id)
                service.category.add(category)
            messages.success(request, 'Service created successfully')
            return render(request, 'users/success.html')
        except:
            messages.error(request, 'Failed To Create Service')
            return render(request, 'services/create_service.html')
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'services/create_service.html', context)


@login_required
def service_details(request, id):
    service = Service.objects.get(id=id)
    all_reviews = Review.objects.filter(service=service)
    paginator = Paginator(all_reviews, 3)
    page = request.GET.get('page')
    reviews = paginator.get_page(page)
    order_exists = Order.objects.filter(buyer=request.user.userprofile, service=service).exists()
    context = {
        'service': service, 'reviews': reviews, 'order_exists': order_exists
    }
    return render(request, 'services/service_deatils.html', context)


def category_services(request, category_id):
    category = Category.objects.get(id=category_id)
    services = Service.objects.all()
    get_services = [service for service in services if category in service.category.all()]
    context = {
        'category': category,
        'services': get_services,
        'services_length': len(get_services)
    }

    return render(request, 'services/category_services.html', context)

def search_view(request):
    query = request.GET.get('q')
    if query:
        services = Service.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
    else:
        services = None
    context = {'services': services, 'query': query, 'services_length': len(services)}

    return render(request, 'services/search_results.html', context)


@login_required
def add_review(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            reviewer = request.user
            service_id = data.get("service_id")
            rating = data.get('rating')
            comment = data.get("comment")
            Review.objects.create(
                reviewer=reviewer, service_id=service_id, rating=rating, comment=comment
            )
            return JsonResponse({'status': 'success', 'message': 'Review Created Successfully'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
    return JsonResponse({'status': "error", 'message': 'Failed to add review'})


@login_required
def request_service(request):
    buyer = request.user.userprofile
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            seller_id = data.get('seller_id')
            service_title = data.get('service_title')
            service_id = data.get('service_id')
            receiver = User.objects.get(id=seller_id)
            seller = UserProfile.objects.get(user=receiver)
            service = Service.objects.get(id=service_id)
            message = f'{request.user.username} requested your service "{service_title}"'
            if Order.objects.filter(buyer=buyer, service_id=service_id).exists():
                return JsonResponse({'status': 'error', 'message': 'Order already exists'})
            Order.objects.create(
                seller=seller, buyer=buyer, service=service
            )
            # create direct message
            DirectMessage.objects.create(
                sender=request.user, receiver=receiver, service=service, message=message
            )
            return JsonResponse({'status': 'success', 'message': 'Order Created Successfully'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
    return JsonResponse({'status': "error", 'message': 'Failed to request order'})

@login_required
def get_home_services(request):
    services = Service.objects.order_by('created').all()
    service_list = []
    average_rating = 0.0

    for service in services:
        # Get the review instances related to the current service
        reviews = Review.objects.filter(service=service)

        # Calculate the average rating for the service if there are reviews
        if reviews.exists():
            total_rating = sum(review.rating for review in reviews)
            average_rating = total_rating / reviews.count()

        # Create a dictionary for the service and its reviews
        service_data = {
            'id': service.id,
            'user': service.user.user.username,
            'title': service.title,
            'picture': service.picture.url,  # Use the URL of the picture
            'price': str(service.price),  # Convert the DecimalField to string for JSON serialization
            'duration_quantity': service.duration_quantity,
            'duration_unit': service.duration_unit,
            'average_rating': average_rating,  # Add the average rating to the service data
            'reviews': [],  # List to store the reviews
        }

        # Add each review's data to the 'reviews' list in the service_data dictionary
        for review in reviews:
            review_data = {
                'reviewer': review.reviewer.username,
                'rating': review.rating,
                'comment': review.comment,
            }
            service_data['reviews'].append(review_data)

        # Add the service_data dictionary to the service_list
        service_list.append(service_data)

    return JsonResponse({'services': service_list})

@login_required
def update_is_read(request, id):
    if request.method == 'POST':
        message = DirectMessage.objects.get(service__id=id)
        message.is_read = True
        message.save()
        return JsonResponse({'status': 'success', 'message': "message updated successfully"})
    return JsonResponse({'status': 'error', 'message': "invalid response"})

services/templates/services/add_category.html
{% extends 'users/base.html' %}

{% block title %}Category Page{% endblock title %}

{% block header %}
  <h2 class="text-center">Add Category</h2>
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}

    <div class="input-group mb-3">
      <span class="input-group-text">
        <i class="fa-solid fa-people-group"></i>
      </span>
      <input type="text" name="category" class="form-control" placeholder="Enter Category Name" aria-label="Username" aria-describedby="basic-addon1" required>
    </div>

    <button type="submit" class="btn btn-success">Add Category</button>
  </form>
{% endblock content %}

services/templates/services/category_services.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}Home | WeConnect App{% endblock title %}

{% block header %}
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block all_content %}
    <h5 class='container'>{{ services_length }} Service{{ services_length|pluralize }} with category "{{ category.name }}" found:</h5>

    {% if services %}
      <div class="pagination-wrapper">
        <div class="pagination">
          <span class="step-links">
            {% if services.has_previous %}
              <a href="?page={{ services.previous_page_number }}"><i class="fa-solid fa-arrow-left"></i></a>
            {% endif %}

            {% if services.has_next %}
              <a href="?page={{ services.next_page_number }}"><i class="fa-solid fa-arrow-right"></i></a>
            {% endif %}
          </span>
        </div>
      </div>
  
      <div class="container text-center">
        <div class="row">
          {% for service in services %}
            <div class="col">
              <a class="link-underline-light link-dark" href="{% url 'services:service_details' service.id %}">
                <div class="card mb-2" style="width: 15rem;">
                  <img src="{{ service.picture.url }}" class="card-img-top service_image" alt="...">
                  <div style="display: flex; flex-grow: 1; justify-content: space-between; align-items: center;">
                    <div style="display: flex; flex-direction: row;">
                      <img src="{{ service.user.profile_pics.url }}" alt="Profile Picture" style="width: 40px; height: 40px; border-radius: 50%; margin-right: 10px;">
                      <h6 class="card-subtitle text-body-secondary">{{ service.user.user.username}}</h6>
                    </div>
                    <h6 class="card-subtitle text-body-secondary">Level {{ service.user.level }}</h6>        
                  </div>
                  <div class="card-body">
                    <h6 class="card-title">{{ service.title }}</h6>
                    <div style="display: flex; justify-content: space-between;">
                      <div style="display: flex; flex-direction: row;">
                        <p class="card-subtitle text-body-secondary text-start"><i class="fa-solid fa-star"></i></p>
                        <p>{{ service.average_rating }} ({{ service.total_reviews }})</p>
                      </div>
                      <p><strong>From <i class="fa-solid fa-naira-sign"></i>{{ service.price }}</strong></p>
                    </div>
                    <div style="display: flex; justify-content: space-between; text-decoration: none">
                      {% for category in service.category.all %}
                        <a id="category_link" href="{% url 'services:category_services' category.id %}" class="card-link">{{ category.name }}</a>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    {% else %}
      <p>No Service Content </p>
    {% endif %}

{% endblock all_content %}

services/templates/services/create_service.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}Service Page{% endblock title %}

{% block header %}
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
  <h2 class="text-center">Create a service or product to sell</h2>
{% endblock header %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Choose category for your service:</p>
    {% for category in categories %}
      <div class="form-check form-check-inline mb-3">
        <input class="form-check-input" type="checkbox" id="inlineCheckbox1" name="categories" value="{{ category.id }}">
        <label class="form-check-label" for="inlineCheckbox1">{{ category.name }}</label>
      </div>
    {% endfor %}

    <div class="input-group mb-3">
      <span class="input-group-text">
        <i class="fa-solid fa-closed-captioning"></i>
      </span>
      <input type="text" name="title" class="form-control" placeholder="Title of your service" maxlength="100" required>
    </div>

    <div class="input-group mb-3">
      <span class="input-group-text">
        <i class="fa-solid fa-pencil"></i>
      </span>
      <textarea name="description" placeholder="Give all details about your service/product ..." class="form-control" aria-label="With textarea" rows="5" cols="8" required></textarea>
    </div>

    <div class="input-group mb-3">
      <input type="file" id="image-input" accept="image/*" name="picture" >
    </div>

    <div class="input-group mb-3 image-style">
      <div id="image-preview"></div>
    </div>

    <div class="input-group mb-3">
      <span class="input-group-text">
        <i class="fa-solid fa-naira-sign"></i>
      </span>
      <input type="number" name="price" class="form-control" placeholder="Price for the service (numbers only)" required>
    </div>

    <div class="input-group mb-3">
      <select class="form-select" aria-label="Default select example" name="duration_unit">
        <option disabled selected>I will deliver in ...</option>
        <option value="hours">Hour</option>
        <option value="days">Day</option>
        <option value="weeks">Week</option>
        <option value="months">Month</option>
      </select>
    </div>

    <div class="input-group mb-3">
      <span class="input-group-text">
        <i class="fa-solid fa-clock"></i>
      </span>
      <input type="number" name="duration_quantity" class="form-control" placeholder="How many hours/days/weeks/months?" required>
    </div>

    <button type="submit" class="btn btn-success">Create Service</button>
  </form>
{% endblock content %}

{% block js %}
  <script src="{% static 'js/image_preview.js' %}"></script>
  <script src="{% static 'js/countCharacters.js' %}"></script>
{% endblock js %}

services/templates/services/list_category.html
{% extends 'users/base.html' %}

{% block title %}All Categories{% endblock title %}

{% block header %}
  <h2 class="text-center">All Category List - {{ categories.count }} </h2>
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block content %}
  {% if categories %}
    <ul class="list-group">
      {% for category in categories %}
        <li class="list-group-item">{{ category.name }}</li>
      {% endfor %}
    </ul>
    <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'services:add_category' %}">Add New Category</a>
  {% else %}
    <p>No categories found.</p>
    <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'services:add_category' %}">Add Category</a>
  {% endif %}
{% endblock content %}

services/templates/services/search_results.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}Home | WeConnect App{% endblock title %}

{% block header %}
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block all_content %}
    <h5 class='container'>{{ services_length }} Service{{ services_length|pluralize }} found for search "{{ query }}":</h5>

    {% if services %}
      <div class="pagination-wrapper">
        <div class="pagination">
          <span class="step-links">
            {% if services.has_previous %}
              <a href="?page={{ services.previous_page_number }}"><i class="fa-solid fa-arrow-left"></i></a>
            {% endif %}

            {% if services.has_next %}
              <a href="?page={{ services.next_page_number }}"><i class="fa-solid fa-arrow-right"></i></a>
            {% endif %}
          </span>
        </div>
      </div>
  
      <div class="container text-center">
        <div class="row">
          {% for service in services %}
            <div class="col">
              <a class="link-underline-light link-dark" href="{% url 'services:service_details' service.id %}">
                <div class="card mb-2" style="width: 15rem;">
                  <img src="{{ service.picture.url }}" class="card-img-top service_image" alt="...">
                  <div style="display: flex; flex-grow: 1; justify-content: space-between; align-items: center;">
                    <div style="display: flex; flex-direction: row;">
                      <img src="{{ service.user.profile_pics.url }}" alt="Profile Picture" style="width: 40px; height: 40px; border-radius: 50%; margin-right: 10px;">
                      <h6 class="card-subtitle text-body-secondary">{{ service.user.user.username}}</h6>
                    </div>
                    <h6 class="card-subtitle text-body-secondary">Level {{ service.user.level }}</h6>        
                  </div>
                  <div class="card-body">
                    <h6 class="card-title">{{ service.title }}</h6>
                    <div style="display: flex; justify-content: space-between;">
                      <div style="display: flex; flex-direction: row;">
                        <p class="card-subtitle text-body-secondary text-start"><i class="fa-solid fa-star"></i></p>
                        <p>{{ service.average_rating }} ({{ service.total_reviews }})</p>
                      </div>
                      <p><strong>From <i class="fa-solid fa-naira-sign"></i>{{ service.price }}</strong></p>
                    </div>
                    <div style="display: flex; justify-content: space-between; text-decoration: none">
                      {% for category in service.category.all %}
                        <a id="category_link" href="{% url 'services:category_services' category.id %}" class="card-link">{{ category.name }}</a>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    {% else %}
      <p>No Service Content </p>
    {% endif %}

{% endblock all_content %}

services/templates/services/service_deatils.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}Service Detail Page{% endblock title %}

{% block header %}
  {% if messages %}
    <div class="alert {% if messages.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
      {% for message in messages %}
        <p class="text-center">{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endblock header %}

{% block content %}
<div class=" container card">
  <img src="{{ service.picture.url }}" class="card-img-top" alt="..." style="height: 600px; object-fit: cover;">
  <div class="card-body">
    <h5 class="card-title" id='serviceTitle'>{{ service.title}}</h5>
    <div style="display: flex; justify-content: space-between;">
      <h6 class="card-subtitle text-body-secondary text-start">{{ service.user.user.username}}</h6>
      <div style="display: flex; flex-direction: row;">
        <div class="card-subtitle text-body-secondary text-end rating-container"></div>
        <p>{{ service.average_rating }} ({{ service.total_reviews }})</p>
      </div>
    </div>
    <p class="card-text">{{ service.description }}</p>
    <div style="display: flex; flex-direction: row; justify-content: space-between;">
      <a href="#" class="card-link" id="add_review" data-bs-toggle="modal" data-bs-target="#addReviewModal">Add Review</a>
      {% if service.user != request.user.userprofile %}
        {% if order_exists %}
          <p class='card-link'>Service Requested</p>
        {% else %}
          <a href="#" id="requestLink" class="card-link" onclick="requestService()" data-x="{{ service.user.user.id }}" data-y="{{ service.id }}">Request This Service</a>
        {% endif %}
      {% else %}
        <p> Add number of orders</p>
      {% endif %}
    </div>
  </div>
</div>

<div>
  {% if reviews %}
    <h3>{{ service.total_reviews }} Reviews:</h3>
    {% for review in reviews %}
      <div class="card">
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-body-secondary">@{{ review.reviewer.get_full_name }} says:</h6>
          <p class="card-text">{{ review.comment }}</p>
        </div>
      </div>
    {% endfor %}

    <div class="pagination-wrapper">
      <div class="pagination">
        <span class="step-links">
          {% if reviews.has_previous %}
            <a href="?page={{ reviews.previous_page_number }}">Previous</a>
          {% endif %}

          {% if reviews.has_next %}
            <a href="?page={{ reviews.next_page_number }}">Next</a>
          {% endif %}
        </span>
      </div>
    </div>
  {% else %}
    <p>Be the first to add a review</p>
  {% endif %}
</div>

<!-- Add Review Modal -->
<div class="modal fade" id="addReviewModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Add Review</h1>
        <button type="button" id="closeBtn" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modal_body">
        <input type='hidden' id='service_id' value="{{ service.id }}" />
        <div class="input-group mb-3">
          <select class="form-select" aria-label="Default select example" name="rating" required>
            <option disabled selected>Select A Rating Between 1 To 5</option>
            <option value="1.0">1</option>
            <option value="2.0">2</option>
            <option value="3.0">3</option>
            <option value="4.0">4</option>
            <option value="5.0">5</option>
          </select>
        </div>

        <div class="input-group mb-3">
          <span class="input-group-text">
            <i class="fa-solid fa-pencil"></i>
          </span>
          <textarea name="comment" placeholder="Write your review in 150 characters ..." class="form-control" aria-label="With textarea" maxlength="150" rows="5" cols="8" required></textarea>
        </div>
      </div>
      <div class="modal-footer" id="modalFooter">
        <button type="button" class="btn btn-primary" onclick="addReviews()">Add Review</button>
      </div>
    </div>
  </div>
</div>
<div id="reviewMsg">
  
</div>
{% endblock content %}

{% block js %}
  <script src="{% static 'js/addReviews.js' %}"></script>
  <script src="{% static 'js/displayRating.js' %}"></script>
  <script src="{% static 'js/requestService.js' %}"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const averageRating = {{ service.average_rating|default:0 }};
      displayRating(averageRating);
    })    
  </script>
{% endblock js %}